#pragma once

#include <SlateIMWidgetBase.h>

#include "SimiPerformanceWidget.h"

class SBox;

class FSimiToolbar : public FSlateIMExposedBase
{
public:
	FSimiToolbar();
	virtual ~FSimiToolbar() override;

private:
	// ~Begin FSlateIMExposedBase interface
	virtual void DrawContent(float DeltaTime) override;
	virtual void EnableWidget() override;
	virtual void DisableWidget() override;
	// ~End FSlateIMExposedBase interface

	/**
	 * Callback executed when the exposed widget is changed internally
	 */
	void OnExposedWidgetUpdated(TSharedRef<SWidget> NewWidget);

	/**
	 * Helper widget to be embedded in the layout 
	 * Used to easily update it's content with the widget generated by SlateIM
	 */
	TSharedPtr<SBox> ExposedContent;
	/**
	 * Current widget instance added to the screen
	 */
	TSharedPtr<SWidget> LayoutWidget;
};
